# -*- coding: utf-8 -*-
"""Klasyfikacja_drzewa_decyzyjne.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t-03doL-wotOGP2d6P_akvN6zFqLdd0O

# Klasyfikacja z wykorzystaniem modeli opartymi o drzewa decyzyjnyjne

## Wczytywanie danych w sparku

Utworzenie środowiska pyspark do obliczeń:
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/PiotrMaciejKowalski/BigData2024Project.git
# %cd BigData2024Project
!git checkout main
# %cd ..

!chmod 755 /content/BigData2024Project/src/setup.sh
!/content/BigData2024Project/src/setup.sh

import sys
sys.path.append('/content/BigData2024Project/src')

from start_spark import initialize_spark
initialize_spark()

import pandas as pd
from pyspark.sql import SparkSession

from big_mess.loaders import default_loader, load_single_month, load_anotated, save_to_csv, preprocessed_loader

spark = SparkSession.builder\
        .master("local")\
        .appName("Colab")\
        .config('spark.ui.port', '4050')\
        .getOrCreate()

"""## Budowa modeli drzew decyzyjnych

**Cel**:

Celem jest zbudowanie modeli do klasyfikacji czy wskazany punkt lokalizacyjny ze zbioru danych NASA jest: pustynia, stepem lub innym obszarem. Zbudowane zostana trzy rodzaje modeli:

* Detekcja pustynia - step - inne
* Detekcja pustynia - niepustynia
* Detekcja step - niestep

Dla kazdego z miesiecy powstanie jeden model kazdego rodzaju.

**Proba danych**:

Dane wykorzystane do modelowania zostały stworzone po przez połączenie dwoch zbiorow danych:

* 1193 lokalizacji *lon* i *lat* z określoną flagą 0, 1 w kolumnach *pustynia* lub *step* (reczna adnotacja)
* danych NASA w podziale na miesiące. Od *pazdziernika 2022* do  *wrzesnia 2023*

**Metoda**:

Do modelowania uzyto metody drzew decyzyjnych.

### Import bibliotek
"""

!pip install datashader
!pip install holoviews hvplot colorcet
!pip install geoviews

from typing import List, Optional, Tuple, Any
import pickle
import pandas as pd
import numpy as np
import matplotlib.colors as mpl_colors
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report, recall_score, precision_score, f1_score
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.feature_selection import mutual_info_classif
from imblearn.over_sampling import RandomOverSampler, SMOTE
from lightgbm import LGBMClassifier
import datashader as ds
import datashader.transfer_functions as tf
import colorcet as cc
import holoviews as hv
from holoviews.operation.datashader import datashade
import geoviews as gv
import geoviews.tile_sources as gts
from holoviews import opts
from IPython.display import IFrame
from bokeh.plotting import show, output_notebook

"""### Przygotowanie danych

Na podstawie wczesniej przygotowanych plikow .csv z anotowanymi danymi dla kazdego miesiaca tworzymy liste data framow.
"""

list_of_files = ['nasa_anotated_202301.csv',
                 'nasa_anotated_202302.csv',
                 'nasa_anotated_202303.csv',
                 'nasa_anotated_202304.csv',
                 'nasa_anotated_202305.csv',
                 'nasa_anotated_202306.csv',
                 'nasa_anotated_202307.csv',
                 'nasa_anotated_202308.csv',
                 'nasa_anotated_202309.csv',
                 'nasa_anotated_202210.csv',
                 'nasa_anotated_202211.csv',
                 'nasa_anotated_202212.csv'
                 ]

list_of_anotated_data = [preprocessed_loader(spark, '/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/Anotated_data_12m/' + file) for file in list_of_files]

list_of_df_all = [anotated_data.toPandas() for anotated_data in list_of_anotated_data]

"""Dodanie do danych z kazdego miesiaca kolumny *klasa* z nastepujacym oslownikowaniem:

* **1** - pustynia
* **2** - step
* **3** - inne
"""

for df in list_of_df_all:
  df['klasa'] = np.where(
                        df['pustynia'] == 1, 1, np.where(
                        df['step'] == 1, 2, 3)
                        )

"""Przykladowa ramka danych."""

list_of_df_all[0].head()

"""Liczebnosci poszczegolnych klas w probce."""

{1:list_of_df_all[0]['pustynia'].sum(), 2:list_of_df_all[0]['step'].sum() , 3:list_of_df_all[0]['pustynia'].count() - list_of_df_all[0]['pustynia'].sum()- list_of_df_all[0]['step'].sum()}

"""Lista z danymi z kazdego miesiaca, do wizualizacji na mapach."""

daty = [(2023,1), (2023,2), (2023,3), (2023,4), (2023,5), (2023,6), (2023,7), (2023,8), (2023,9), (2022,10), (2022,11), (2022,12)]

list_df_months = [load_single_month(spark, year=year, month=month).toPandas() for year, month in daty]

"""#### Wydzielenie zbiorow danych

Wydzielenie danych z etykietami do odpowiednich modeli oraz przygotowanie listy ramek danych z cechami badanych obszarow.

Cechy:

* **GVEG** - wskaznik roslinnosci
* **Rainf** - wskaznik opadow deszczu
* **Evap** - wskaznik calkowitej ewapotranspiracji
* **AvgSurfT** - wskaznik sredniej temperatury powierzchni ziemi
* **Albedo** - wskaznik albedo
* **SoilT_40_100cm** - wskaznik temperatury gleby w warstwie o glebokosci od 40 do 100 cm
* **PotEvap** - wskaznik potencjalnej ewapotranspiracji
* **RootMoist** - wilgotnosć gleby w strefie korzeniowej (parowanie, ktore mialoby miejsce, gdyby dostepne bylo wystarczajace zrodlo wody)
* **SoilM_100_200cm** - wilgotnosc gleby w warstwie o glebokosci od 100 do 200 cm
"""

y_m1 = list_of_df_all[0]['klasa']
y_m2 = list_of_df_all[0]['pustynia']
y_m3 = list_of_df_all[0]['step']

list_of_df = [df.loc[:,'Rainf':'SoilM_100_200cm'] for df in list_of_df_all]

"""#### Definiowanie funkcji"""

def create_models(params_gs: dict, list_of_df: List[pd.DataFrame], scoring: Optional[str] = 'accuracy') -> tuple[List, List]:
  list_params = []
  list_of_models = []
  number_of_data = len(list_of_df)

  for i in range(number_of_data):
    gs = GridSearchCV(tree.DecisionTreeClassifier(random_state = 2024), cv = 5, param_grid = params_gs, scoring = scoring)
    gs.fit(list_of_df[i][0], list_of_df[i][1])
    list_params.append(gs.best_params_)

  for i in range(number_of_data):
    list_of_models.append(tree.DecisionTreeClassifier(random_state = 2024, **list_params[i]))

  for i in range(number_of_data):
    list_of_models[i].fit(list_of_df[i][0], list_of_df[i][1])

  return list_of_models, list_params

def summary_model(model: Any, X:pd.DataFrame, y:pd.DataFrame, labels_names: List) -> None:
  y_pred = model.predict(X)
  y_real= y
  cf_matrix = confusion_matrix(y_real, y_pred)
  group_counts = ["{0:0.0f}".format(value) for value in cf_matrix.flatten()]
  group_percentages = ["{0:.2%}".format(value) for value in cf_matrix.flatten()/np.sum(cf_matrix)]
  labels = [f"{v1}\n{v2}" for v1, v2 in zip(group_counts,group_percentages)]
  labels = np.asarray(labels).reshape(len(labels_names),len(labels_names))
  sns.heatmap(cf_matrix, annot=labels, fmt='', cmap='Reds',xticklabels=labels_names,yticklabels=labels_names)
  plt.xlabel('Predykcja')
  plt.ylabel('Rzeczywistość')
  plt.show()

def print_classification_report(model: Any, X: pd.DataFrame, y: pd.DataFrame) -> None:
  y_predict = model.predict(X)
  print(classification_report(y, y_predict))

def print_accuracy_heatmap(list_of_models: List[Any], list_of_X_test: List[pd.DataFrame], y_test: List[pd.DataFrame]) -> None:
  list_accuracy = []
  for i in range(12):
    temp = []
    for j in range(12):
      temp.append(list_of_models[i].score(list_of_X_test[j],  y_test) *100)
    list_accuracy.append(temp)
  miesiace = ['STY', 'LUT', 'MAR', 'KWI', 'MAJ', 'CZE', 'LIP', 'SIE', 'WRZ', 'PAZ', 'LIS', 'GRU']
  df_accuracy =pd.DataFrame(list_accuracy, index=miesiace, columns=miesiace)
  plt.figure(figsize=(10,8))
  sns.heatmap(df_accuracy, annot=True)
  plt.xlabel('Miesiace - test')
  plt.ylabel('Miesiace - model')
  plt.title("Accuracy")

def print_recall_heatmap(list_of_models: List[Any], list_of_X_test: List[pd.DataFrame], y_test: List[pd.DataFrame]) -> None:
  list_recall = []
  for i in range(12):
    temp = []
    for j in range(12):
      y_pred = list_of_models[i].predict(list_of_X_test[j])
      temp.append(recall_score(y_pred,  y_test) *100)
    list_recall.append(temp)
  miesiace = ['STY', 'LUT', 'MAR', 'KWI', 'MAJ', 'CZE', 'LIP', 'SIE', 'WRZ', 'PAZ', 'LIS', 'GRU']
  df_recall =pd.DataFrame(list_recall, index=miesiace, columns=miesiace)
  plt.figure(figsize=(10,8))
  sns.heatmap(df_recall, annot=True)
  plt.xlabel('Miesiace - test')
  plt.ylabel('Miesiace - model')
  plt.title("Recall")

def print_precision_heatmap(list_of_models: List[Any], list_of_X_test: List[pd.DataFrame], y_test: List[pd.DataFrame]) -> None:
  list_precision = []
  for i in range(12):
    temp = []
    for j in range(12):
      y_pred = list_of_models[i].predict(list_of_X_test[j])
      temp.append(precision_score(y_pred,  y_test) *100)
    list_precision.append(temp)
  miesiace = ['STY', 'LUT', 'MAR', 'KWI', 'MAJ', 'CZE', 'LIP', 'SIE', 'WRZ', 'PAZ', 'LIS', 'GRU']
  df_precision =pd.DataFrame(list_precision, index=miesiace, columns=miesiace)
  plt.figure(figsize=(10,8))
  sns.heatmap(df_precision, annot=True)
  plt.xlabel('Miesiace - test')
  plt.ylabel('Miesiace - model')
  plt.title("Precision")

def print_f1_heatmap(list_of_models: List[Any], list_of_X_test: List[pd.DataFrame], y_test: List[pd.DataFrame]) -> None:
  list_f1 = []
  for i in range(12):
    temp = []
    for j in range(12):
      y_pred = list_of_models[i].predict(list_of_X_test[j])
      temp.append(f1_score(y_pred,  y_test) *100)
    list_f1.append(temp)
  miesiace = ['STY', 'LUT', 'MAR', 'KWI', 'MAJ', 'CZE', 'LIP', 'SIE', 'WRZ', 'PAZ', 'LIS', 'GRU']
  df_f1 =pd.DataFrame(list_f1, index=miesiace, columns=miesiace)
  plt.figure(figsize=(10,8))
  sns.heatmap(df_f1, annot=True)
  plt.xlabel('Miesiace - test')
  plt.ylabel('Miesiace - model')
  plt.title("F1")

class BalanceDataSet():
  '''
  Two techniques for handling imbalanced data.
  '''
  def __init__(
      self,
      X: pd.DataFrame,
      y: pd.DataFrame
      ) -> None:
      self.X = X
      self.y = y
      assert len(self.X)==len(self.y)

  def useOverSampling(
      self,
      randon_seed: Optional[int] = 2023
      ) -> Tuple[pd.DataFrame, pd.DataFrame]:
    oversample = RandomOverSampler( sampling_strategy='auto',
                  random_state=randon_seed)
    return oversample.fit_resample(self.X, self.y)

  def useSMOTE(
      self,
      randon_seed: Optional[int] = 2023
      ) -> Tuple[pd.DataFrame, pd.DataFrame]:
    smote = SMOTE(random_state=randon_seed)
    return smote.fit_resample(self.X, self.y)

def get_colormap(values: list, colors_palette: list, name = 'custom'):
    """
    Funkcja jako argumenty bierze liste wartosci okreslajacych granice przedzialow liczbowych, ktore
    beda okreslac jak dla rozwazanego parametru maja zmieniac się kolory punktow, ktorych lista stanowi
    drugi argument funkcji.
    """
    values = np.sort(np.array(values))
    values = np.interp(values, (values.min(), values.max()), (0, 1))
    cmap = mpl_colors.LinearSegmentedColormap.from_list(name, list(zip(values, colors_palette)))
    return cmap

def plot_map(df: pd.DataFrame, parameter_name: str, colormap: mpl_colors.LinearSegmentedColormap, title: str,
             point_size: int = 8, width: int = 800, height: int = 500, alpha: float = 1,
             bgcolor: str = 'white', colorbar_verbose: bool = True):

    gdf = gv.Points(df, ['lon', 'lat'], [parameter_name]) # obiekt zawierający punkty
    tiles = gts.OSM # wybór mapy tła, w tym wypadku OpenStreetMap

    # łączenie mapy tła z punktami i ustawienie wybranych parametrów wizualizacji
    map_with_points = tiles * gdf.opts(
        title=title,
        color=parameter_name,
        cmap=colormap,
        size=point_size,
        width=width,
        height=height,
        colorbar=colorbar_verbose,
        toolbar='above',
        tools=['hover', 'wheel_zoom', 'reset'],
        alpha=alpha, # przezroczystość
        bgcolor=bgcolor
    )
    return hv.render(map_with_points)

def plot_map_from_model(model, df: pd.DataFrame, title:Optional[str]='', col:Optional[int] = 1 ) -> None:
  assert col in [-1,1]
  df['Model'] = model.predict(df.loc[:,'Rainf':'SoilM_100_200cm'])
  colormap_cluster = get_colormap([0, max(df.Model.values)], ['darkgreen', 'yellow'][::col])
  plot = plot_map(df=df, parameter_name='Model', colormap=colormap_cluster, title=title, alpha=1)
  output_notebook()
  show(plot)

"""### Model 1 - detekcja pustynia - step - inne

#### Podzial na zbior treningowy i testowy
"""

number_of_data = len(list_of_df)

list_of_df_m1 = []

for i in range(number_of_data):
  list_of_df_m1.append(train_test_split(list_of_df[i], y_m1, test_size=0.2, random_state=2024))

list_of_df_m1_tr = [[i[0],i[2]] for i in list_of_df_m1]

list_of_df_m1_te = [[i[1],i[3]] for i in list_of_df_m1]

"""#### Zbalansowanie datasetow

Graficzne przedstawienie liczebnosci kazdej z klas w zbiorze testowym.
"""

plot_data_dist(list_of_df_m1_tr[0][1])

"""Balansujemy kazdy ze zbiorow."""

for i in range(number_of_data):
  list_of_df_m1_tr[i][0], list_of_df_m1_tr[i][1] = BalanceDataSet(list_of_df_m1_tr[i][0], list_of_df_m1_tr[i][1]).useSMOTE()

"""Przykladowe dane po zbalansowaniu."""

plot_data_dist(list_of_df_m1_tr[0][1])

"""#### Drzewa decyzyjne

Zdefiniujmy slownik paramentow drzewa ktory bedzie wykorzystany w metodzie GridSearchCV.
"""

params_gs_m1 = {'criterion': ('entropy', 'gini'),
            'max_depth': np.arange(6,15),
            'min_samples_split': np.arange(6,14),
            'min_samples_leaf': np.arange(3,8)}

"""Utworzenie listy modeli.


"""

list_of_models_m1, list_params_m1 = create_models(params_gs_m1, list_of_df_m1_tr)

"""### Model 2 - detekcja pustynia - niepustynia

#### Podzial na zbior treningowy i testowy
"""

list_of_df_m2 = []

for i in range(number_of_data):
  list_of_df_m2.append(train_test_split(list_of_df[i], y_m2, test_size=0.2, random_state=2024))

list_of_df_m2_tr = [[i[0],i[2]] for i in list_of_df_m2]

list_of_df_m2_te = [[i[1],i[3]] for i in list_of_df_m2]

"""#### Zbalansowanie datasetow

Graficzne przedstawienie liczebnosci kazdej z klas w zbiorze testowym.
"""

plot_data_dist(list_of_df_m2_tr[0][1])

"""Balansujemy kazdy ze zbiorow."""

for i in range(number_of_data):
  list_of_df_m2_tr[i][0], list_of_df_m2_tr[i][1] = BalanceDataSet(list_of_df_m2_tr[i][0], list_of_df_m2_tr[i][1]).useSMOTE()

"""Przykladowe dane po zbalansowaniu."""

plot_data_dist(list_of_df_m2_tr[0][1])

"""#### Drzewa decyzyjne

Zdefiniujmy slownik paramentow drzewa ktory bedzie wykorzystany w metodzie GridSearchCV.
"""

params_gs_m2 = {'criterion': ('entropy', 'gini'),
            'max_depth': np.arange(6,15),
            'min_samples_split': np.arange(7,16),
            'min_samples_leaf': np.arange(4,11)}

"""Utworzenie listy modeli."""

list_of_models_m2, list_params_m2 = create_models(params_gs_m2, list_of_df_m2_tr, 'accuracy')

"""### Model 3 - detekcja step - niestep

#### Podzial na zbior treningowy i testowy
"""

list_of_df_m3 = []

for i in range(number_of_data):
  list_of_df_m3.append(train_test_split(list_of_df[i], y_m3, test_size=0.2, random_state=2024))

list_of_df_m3_tr = [[i[0],i[2]] for i in list_of_df_m3]

list_of_df_m3_te = [[i[1],i[3]] for i in list_of_df_m3]

"""#### Zbalansowanie datasetow

Graficzne przedstawienie liczebnosci kazdej z klas w zbiorze testowym.
"""

plot_data_dist(list_of_df_m3_tr[0][1])

"""Balansujemy kazdy ze zbiorow."""

for i in range(number_of_data):
  list_of_df_m3_tr[i][0], list_of_df_m3_tr[i][1] = BalanceDataSet(list_of_df_m3_tr[i][0], list_of_df_m3_tr[i][1]).useSMOTE()

"""Przykladowe dane po zbalansowaniu."""

plot_data_dist(list_of_df_m3_tr[0][1])

"""#### Drzewa decyzyjne

Zdefiniujmy slownik paramentow drzewa ktory bedzie wykorzystany w metodzie GridSearchCV.
"""

params_gs_m3 = {'criterion': ('entropy', 'gini'),
            'max_depth': np.arange(6,14),
            'min_samples_split': np.arange(10,14),
            'min_samples_leaf':np.arange(4,10)}

"""Utworzenie listy modeli."""

list_of_models_m3, list_params_m3 = create_models(params_gs_m3, list_of_df_m3_tr, 'accuracy')

"""### Ocena modeli

W tym rozdziale zostana przedstawione mapy ciepla obrazujace wartosci roznych statystyk dla modeli. Wiersze oznaczaja dane miesieczne na ktorych zostal zbudowany model, kolumny dane na ktorych byl testowany.

 Dla kazdego rodzaju modeli, zostanie wybrany najlepszy klasyfikator i dodatkowo sprawdzony.

#### Model 1 - detekcja pustynia - step - inne

Accuracy na zbiorze treningowym.
"""

print_accuracy_heatmap(list_of_models_m1, [i[0] for i in list_of_df_m1_tr], list_of_df_m1_tr[0][1])

"""Accuracy na zbiorze testowym."""

print_accuracy_heatmap(list_of_models_m1, [i[0] for i in list_of_df_m1_te], list_of_df_m1_te[0][1])

"""##### Wnioski

Wnioskujemy, ze w znaczacej liczbie przypadkow zbudowanie modelu uzywajac danych dla miesiaca na ktorym jest testowany, przynosi najlepsze efekty. Sposrod zbudowanych modeli najlepszy wydaje sie ten zbudowany na danych czerwcowych, na zbiorze testowym jego wynik wynosi 84%.

**Podsumowanie dla zbudowanego modelu na danych czerwcowych.**

Zbior treningowy
"""

summary_model(list_of_models_m1[5], list_of_df_m1_tr[5][0], list_of_df_m1_tr[5][1], ['1','2','3'])
print_classification_report(list_of_models_m1[5], list_of_df_m1_tr[5][0], list_of_df_m1_tr[5][1])

"""Zbior testowy"""

summary_model(list_of_models_m1[5], list_of_df_m1_te[5][0], list_of_df_m1_te[5][1], ['1','2','3'])
print_classification_report(list_of_models_m1[5], list_of_df_m1_te[5][0], list_of_df_m1_te[5][1])

plot_map_from_model(list_of_models_m1[5], list_df_months[5], "Czerwiec - detekcja pustynia (1) - step(2) - inne(3)",-1)

"""Porownujac otrzymana mape z danymi o strukturamch pustyn w Ameryce zauwazamy, ze model nie rozpoznaje zimnych pustyn na granicy USA i Kanady. Klasyfikator myli sie rowniez w okolicy Bahamow - uznaje je za pustynie.

#### Model 2 - detekcja pustynia - niepustynia

Accuracy na zbiorze treningowym.
"""

print_accuracy_heatmap(list_of_models_m2, [i[0] for i in list_of_df_m2_tr], list_of_df_m2_tr[0][1])

"""Accuracy na zbiorze testowym."""

print_accuracy_heatmap(list_of_models_m2, [i[0] for i in list_of_df_m2_te], list_of_df_m2_te[0][1])

"""Recall na zbiorze testowym."""

print_recall_heatmap(list_of_models_m2, [i[0] for i in list_of_df_m2_te], list_of_df_m2_te[0][1])

"""Precision na zbiorze testowym."""

print_precision_heatmap(list_of_models_m2, [i[0] for i in list_of_df_m2_te], list_of_df_m2_te[0][1])

"""F1 na zbiorze testowym."""

print_f1_heatmap(list_of_models_m2, [i[0] for i in list_of_df_m2_te], list_of_df_m2_te[0][1])

"""##### Wnioski

Najlepszy wynik klasyfikacji osiagamy na danych z sierpnia. Accuarcy na zbiorze testowym wynosi wowczas 90%.

**Podsumowanie dla zbudowanego modelu na danych serpniowych.**

Zbior treningowy
"""

summary_model(list_of_models_m2[7], list_of_df_m2_tr[7][0], list_of_df_m2_tr[7][1], ['0','1'])
print_classification_report(list_of_models_m2[7], list_of_df_m2_tr[7][0], list_of_df_m2_tr[7][1])

"""Zbior testowy"""

summary_model(list_of_models_m2[7], list_of_df_m2_te[7][0], list_of_df_m2_te[7][1], ['0','1'])
print_classification_report(list_of_models_m2[7], list_of_df_m2_te[7][0], list_of_df_m2_te[7][1])

plot_map_from_model(list_of_models_m2[7], list_df_months[7], "Sierpien - detekcja pustynia (1) - niepustynia (0)")

"""Porownujac otrzymana mape z danymi o strukturamch pustyn w Ameryce zauwazamy, ze model nie rozpoznaje jednej z zimnowych pustyn na granicy USA i Kanady. Klasyfikator myli sie podobnie w okolicy Bahamow - uznaje je za pustynie oraz nad Zatoka Meksykanska.

#### Model 3 - detekcja step - niestep

Accuracy na zbiorze treningowym.
"""

print_accuracy_heatmap(list_of_models_m3, [i[0] for i in list_of_df_m3_tr], list_of_df_m3_tr[0][1])

"""Accuracy na zbiorze testowym."""

print_accuracy_heatmap(list_of_models_m3, [i[0] for i in list_of_df_m3_te], list_of_df_m3_te[0][1])

"""Recall na zbiorze testowym."""

print_recall_heatmap(list_of_models_m3, [i[0] for i in list_of_df_m3_te], list_of_df_m3_te[0][1])

"""Precision na zbiorze testowym."""

print_precision_heatmap(list_of_models_m3, [i[0] for i in list_of_df_m3_te], list_of_df_m3_te[0][1])

"""F1 na zbiorze testowym."""

print_f1_heatmap(list_of_models_m3, [i[0] for i in list_of_df_m3_te], list_of_df_m3_te[0][1])

"""##### Wnioski

Najlepszy wynik klasyfikacji osiagamy na danych z czerwca. Accuarcy na zbiorze testowym wynosi wowczas 85%. Jak zobaczymy na kolejnej mapie, klasyfikator uznaje czesc pustyn za stepy.

**Podsumowanie dla zbudowanego modelu na danych czerwcowych.**

Zbior treningowy
"""

summary_model(list_of_models_m3[5], list_of_df_m3_tr[5][0], list_of_df_m3_tr[5][1], ['0','1'])
print_classification_report(list_of_models_m3[5], list_of_df_m3_tr[5][0], list_of_df_m3_tr[5][1])

"""Zbior testowy"""

summary_model(list_of_models_m3[5], list_of_df_m3_te[5][0], list_of_df_m3_te[5][1], ['0','1'])
print_classification_report(list_of_models_m3[5], list_of_df_m3_te[5][0], list_of_df_m3_te[5][1])

plot_map_from_model(list_of_models_m3[5], list_df_months[5],"Czerwiec - detekcja step (1) - niestep (0)")

"""Klasyfikacja mozna uznać za poprawna, niektore putynie uznane sa za stepy. Problemem sa małe, rozproszone obszary wschodniej czesci kontynentu, w innych zrodlach nie ma tam stepow.

### Zapisanie modeli
"""

model_m1_path='/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/Model_m1/'
model_m2_path='/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/Model_m2/'
model_m3_path='/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/Model_m3/'

model_names = ['01','02','03','04','05','06','07','08','09','10','11','12']

for i in range(12):
  with open(model_m1_path+model_names[i], 'wb') as files:
    pickle.dump(list_of_models_m1[i], files)

for i in range(12):
  with open(model_m2_path+model_names[i], 'wb') as files:
    pickle.dump(list_of_models_m2[i], files)

for i in range(12):
  with open(model_m3_path+model_names[i], 'wb') as files:
    pickle.dump(list_of_models_m3[i], files)

"""## Przedstawienie wynikow na mapach"""

display(IFrame("https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d13982681.959428234!2d-98.66341902257437!3d38.39997874427714!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e1!3m2!1spl!2spl!4v1703000232420!5m2!1spl!2spl", '800px', '500px'))

"""### Dane z 07.2023

Do klasyfikacji wykorzytamy modele zbudowane na danych lipcowych. Dane z tego miesiaca byly uznane przez zespol za najlepsze do identyfikacji terenow pustynnych.
"""

plot_map_from_model(list_of_models_m1[6], list_df_months[6], "Detekcja pustynia (1) - step(2) - inne(3)",-1)

plot_map_from_model(list_of_models_m2[6], list_df_months[6], "Detekcja pustynia (1) - niepustynia (0)")

plot_map_from_model(list_of_models_m3[6], list_df_months[6],"Detekcja step (1) - niestep (0)")

"""### Dane z 06.2023

Do klasyfikacji wykorzystamy modele zbudowane na danych listopadowych. Eksperyment ma na celu przetestowania klasyfikatorow na danych innych niz miesiac ich budowy.
"""

plot_map_from_model(list_of_models_m1[10], list_df_months[5], "Detekcja pustynia (1) - step(2) - inne(3)",-1)

plot_map_from_model(list_of_models_m2[10], list_df_months[5], "Detekcja pustynia (1) - niepustynia (0)")

plot_map_from_model(list_of_models_m3[10], list_df_months[5],"Detekcja step (1) - niestep (0)",1)

"""### Klasyfikacja pustynia-step-inne dla kazdego miesiaca"""

miesiace = ['Styczen - ', 'Luty - ', 'Marzec - ', 'Kwiecien - ', 'Maj - ', 'Czerwiec - ', 'Lipiec - ', 'Sierpien - ', 'Wrzesien - ', 'Pazdziernik - ', 'Listopad - ', 'Grudzien - ']
for i in range(12):
  plot_map_from_model(list_of_models_m1[i], list_df_months[i], miesiace[i]+"detekcja pustynia (1) - step(2) - inne(3)",-1)

"""### Klasyfikacja pustyn dla kazdego miesiaca"""

for i in range(12):
  plot_map_from_model(list_of_models_m2[i], list_df_months[i], miesiace[i]+"detekcja pustynia (1) - niepustynia (0)")

"""## Lasy losowe

**Metoda**:

Do modelowania uzyto metody lasow losowych oraz wykorzytano te miesiace ktore okazly sie najlepsze w modelach drzew decyzyjnych.

Zdefiniujmy slownik paramentow modelu ktory bedzie wykorzystany w metodzie GridSearchCV.
"""

params_gs_las = {'n_estimators': [10,20,30,40,50,60,70,80,90,100,110],
                  'max_depth': np.arange(7,11),
                  'min_samples_leaf': np.arange(4,8)}

"""### Model 1 - detekcja pustynia - step - inne

Model zostanie zbudowany na danych z czerwca.
"""

gs_las_m1 = GridSearchCV(RandomForestClassifier(random_state = 2024), cv = 5, param_grid = params_gs_las, scoring = 'accuracy')
gs_las_m1.fit(list_of_df_m1_tr[5][0], list_of_df_m1_tr[5][1])

las_m1 = RandomForestClassifier(random_state = 2024, **gs_las_m1.best_params_)

las_m1.fit(list_of_df_m1_tr[5][0], list_of_df_m1_tr[5][1])

"""Zbior treningowy"""

summary_model(las_m1, list_of_df_m1_tr[5][0], list_of_df_m1_tr[5][1], ['1','2','3'])
print_classification_report(las_m1, list_of_df_m1_tr[5][0], list_of_df_m1_tr[5][1])

"""Zbior testowy"""

summary_model(las_m1, list_of_df_m1_te[5][0], list_of_df_m1_te[5][1], ['1','2','3'])
print_classification_report(las_m1, list_of_df_m1_te[5][0], list_of_df_m1_te[5][1])

plot_map_from_model(las_m1, list_df_months[5], "Czerwiec - detekcja pustynia (1) - step(2) - inne(3)",-1)

"""Model o wynikach podobnych do modelu drzew decyzyjnych.

### Model 2 - detekcja pustynia - niepustynia

Model zostanie zbudowany na danych z lipca oraz sierpnia. Dla sierpnia byly najlepsze wyniki w drzewach, lipiec byl drugi.

**Sierpien**
"""

gs_las_m2 = GridSearchCV(RandomForestClassifier(random_state = 2024), cv = 5, param_grid = params_gs_las, scoring = 'accuracy')
gs_las_m2.fit(list_of_df_m2_tr[7][0], list_of_df_m2_tr[7][1])

las_m2 = RandomForestClassifier(random_state = 2024, **gs_las_m2.best_params_)

las_m2.fit(list_of_df_m2_tr[7][0], list_of_df_m2_tr[7][1])

"""Zbior treningowy"""

summary_model(las_m2, list_of_df_m2_tr[7][0], list_of_df_m2_tr[7][1], ['0','1'])
print_classification_report(las_m2, list_of_df_m2_tr[7][0], list_of_df_m2_tr[7][1])

"""Zbior testowy"""

summary_model(las_m2, list_of_df_m2_te[7][0], list_of_df_m2_te[7][1], ['0','1'])
print_classification_report(las_m2, list_of_df_m2_te[7][0], list_of_df_m2_te[7][1])

plot_map_from_model(las_m2, list_df_months[7], "Sierpien - detekcja pustynia (1) - niepustynia (0)")

"""**Lipiec**"""

gs_las_m2_7 = GridSearchCV(RandomForestClassifier(random_state = 2024), cv = 5, param_grid = params_gs_las, scoring = 'accuracy')
gs_las_m2_7.fit(list_of_df_m2_tr[6][0], list_of_df_m2_tr[6][1])

gs_las_m2_7.best_params_

las_m2_7 = RandomForestClassifier(random_state = 2024, **gs_las_m2_7.best_params_)

las_m2_7.fit(list_of_df_m2_tr[6][0], list_of_df_m2_tr[6][1])

"""Zbior treningowy"""

summary_model(las_m2_7, list_of_df_m2_tr[6][0], list_of_df_m2_tr[6][1], ['0','1'])
print_classification_report(las_m2_7, list_of_df_m2_tr[6][0], list_of_df_m2_tr[6][1])

"""Zbior testowy"""

summary_model(las_m2_7, list_of_df_m2_te[6][0], list_of_df_m2_te[6][1], ['0','1'])
print_classification_report(las_m2_7, list_of_df_m2_te[6][0], list_of_df_m2_te[6][1])

plot_map_from_model(las_m2_7, list_df_months[6], "Lipiec - detekcja pustynia (1) - niepustynia (0)")

"""Lepsze wyniki otrzymano dla danych z lipca. Model osiągnal 92% accuracy, 89% precision oraz 57% recall. Klasyfikator lasow losowych zbudowany na tych danych wydaje sie być jednym z lepszych. Widac sklasyfikowane zimne pustynie na granicy USA i Kandy. Nieprawidlowo sklasyfikowano obszary nad Zatoka Meksykanska.

### Model 3 - detekcja step - niestep

Model zostanie zbudowany na danych z czerwca.
"""

gs_las_m3 = GridSearchCV(RandomForestClassifier(random_state = 2024), cv = 5, param_grid = params_gs_las, scoring = 'accuracy')
gs_las_m3.fit(list_of_df_m3_tr[5][0], list_of_df_m3_tr[5][1])

las_m3 = RandomForestClassifier(random_state = 2024, **gs_las_m3.best_params_)

las_m3.fit(list_of_df_m3_tr[5][0], list_of_df_m3_tr[5][1])

"""Zbior treningowy"""

summary_model(las_m3, list_of_df_m3_tr[5][0], list_of_df_m3_tr[5][1], ['0','1'])
print_classification_report(las_m3, list_of_df_m3_tr[5][0], list_of_df_m3_tr[5][1])

"""Zbior testowy"""

summary_model(las_m3, list_of_df_m3_te[5][0], list_of_df_m3_te[5][1], ['0','1'])
print_classification_report(las_m3, list_of_df_m3_te[5][0], list_of_df_m3_te[5][1])

plot_map_from_model(las_m3, list_df_months[5], "Czerwiec - detekcja step (1) - niestep (0)")

"""Model nieznacznie lepszy od modelu drzew decyzyjnych zbudowanego na tym samym miesiacu. Udalo sie zdecydowanie ograniczyc liczbe obszarow uznanych za stepy w wschodniej czesci kontynentu.

### Zapisanie modeli
"""

model_las_m1_path='/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/Lasy/las_m1'
model_las_m2_path='/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/Lasy/las_m2'
model_las_m2_7_path='/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/Lasy/las_m2_7'
model_las_m3_path='/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/Lasy/las_m3'

with open(model_las_m1_path, 'wb') as files:
  pickle.dump(las_m1, files)

with open(model_las_m2_path, 'wb') as files:
  pickle.dump(las_m2, files)

with open(model_las_m2_7_path, 'wb') as files:
  pickle.dump(las_m2_7, files)

with open(model_las_m3_path, 'wb') as files:
  pickle.dump(las_m3, files)

"""## Light GBM

**Metoda**:

Do modelowania uzyto metody LightGBM oraz wykorzytano te miesiace ktore okazly sie najlepsze w modelach drzew decyzyjnych.

Zdefiniujmy slownik paramentow modelu ktory bedzie wykorzystany w metodzie GridSearchCV.
"""

params_gs_lgbm = {'n_estimators':  [10,50,100,120],
                  'num_leaves': [10,20,30,40],
                  'max_depth': np.arange(5,11)}

"""### Model 1 - detekcja pustynia - step - inne

Model zostanie zbudowany na danych z czerwca.
"""

gs_lgbm_m1 = GridSearchCV(LGBMClassifier(random_state = 2024), cv = 5, param_grid = params_gs_lgbm, scoring = 'accuracy')
gs_lgbm_m1.fit(list_of_df_m1_tr[5][0], list_of_df_m1_tr[5][1])

lgbm_m1 = LGBMClassifier(random_state = 2024,**gs_lgbm_m1.best_params_)

lgbm_m1.fit(list_of_df_m1_tr[5][0], list_of_df_m1_tr[5][1])

"""Zbior treningowy"""

summary_model(lgbm_m1, list_of_df_m1_tr[5][0], list_of_df_m1_tr[5][1], ['1','2','3'])
print_classification_report(lgbm_m1, list_of_df_m1_tr[5][0], list_of_df_m1_tr[5][1])

"""Zbior testowy"""

summary_model(lgbm_m1, list_of_df_m1_te[5][0], list_of_df_m1_te[5][1], ['1','2','3'])
print_classification_report(lgbm_m1, list_of_df_m1_te[5][0], list_of_df_m1_te[5][1])

plot_map_from_model(lgbm_m1, list_df_months[5], "Czerwiec - detekcja pustynia (1) - step(2) - inne(3)",-1)

"""Model o wynikach podobnych do modelu drzew decyzyjnych i lasow losowych. Widac ograniczenie w klasyfikacji pustyn w okolocy Bahamow.

### Model 2 - detekcja pustynia - niepustynia

Model zostanie zbudowany na danych z lipca oraz sierpnia. Dla sierpnia byly najlepsze wyniki w drzewach, lipiec byl drugi.

**Sierpien**
"""

gs_lgbm_m2 = GridSearchCV(LGBMClassifier(random_state = 2024), cv = 5, param_grid = params_gs_lgbm, scoring = 'accuracy')
gs_lgbm_m2.fit(list_of_df_m2_tr[7][0], list_of_df_m2_tr[7][1])

lgbm_m2 = LGBMClassifier(random_state = 2024, **gs_lgbm_m2.best_params_)

lgbm_m2.fit(list_of_df_m2_tr[7][0], list_of_df_m2_tr[7][1])

"""Zbior treningowy"""

summary_model(lgbm_m2, list_of_df_m2_tr[7][0], list_of_df_m2_tr[7][1], ['0','1'])
print_classification_report(lgbm_m2, list_of_df_m2_tr[7][0], list_of_df_m2_tr[7][1])

"""Zbior testowy"""

summary_model(lgbm_m2, list_of_df_m2_te[7][0], list_of_df_m2_te[7][1], ['0','1'])
print_classification_report(lgbm_m2, list_of_df_m2_te[7][0], list_of_df_m2_te[7][1])

plot_map_from_model(lgbm_m2, list_df_months[7], "Sierpien - detekcja pustynia (1) - niepustynia (0)")

"""**Lipiec**"""

gs_lgbm_m2_7 = GridSearchCV(LGBMClassifier(random_state = 2024), cv = 5, param_grid = params_gs_lgbm, scoring = 'accuracy')
gs_lgbm_m2_7.fit(list_of_df_m2_tr[6][0], list_of_df_m2_tr[6][1])

lgbm_m2_7 = LGBMClassifier(random_state = 2024, **gs_lgbm_m2_7.best_params_)

lgbm_m2_7.fit(list_of_df_m2_tr[6][0], list_of_df_m2_tr[6][1])

gs_lgbm_m2_7.best_params_

"""Zbior treningowy"""

summary_model(lgbm_m2_7, list_of_df_m2_tr[6][0], list_of_df_m2_tr[6][1], ['0','1'])
print_classification_report(lgbm_m2_7, list_of_df_m2_tr[6][0], list_of_df_m2_tr[6][1])

"""Zbior testowy"""

summary_model(lgbm_m2_7, list_of_df_m2_te[6][0], list_of_df_m2_te[6][1], ['0','1'])
print_classification_report(lgbm_m2_7, list_of_df_m2_te[6][0], list_of_df_m2_te[6][1])

plot_map_from_model(lgbm_m2_7, list_df_months[6], "Lipiec - detekcja pustynia (1) - niepustynia (0)")

"""Lepsze wyniki otrzymano dla danych z lipca. W porownaniu do modeli drzew i lasow ten kalsyfikator dziala lepiej w rejonie Zatoki Meksykanskiej, jednak minimalnie gorzej klasyfikuje pustynie zimne.

### Model 3 - detekcja step - niestep

Model zostanie zbudowany na danych z czerwca.
"""

gs_lgbm_m3 = GridSearchCV(LGBMClassifier(random_state = 2024), cv = 5, param_grid = params_gs_lgbm, scoring = 'accuracy')
gs_lgbm_m3.fit(list_of_df_m3_tr[5][0], list_of_df_m3_tr[5][1])

lgbm_m3 = LGBMClassifier(random_state = 2024, **gs_lgbm_m3.best_params_)

lgbm_m3.fit(list_of_df_m3_tr[5][0], list_of_df_m3_tr[5][1])

"""Zbior treningowy"""

summary_model(lgbm_m3, list_of_df_m3_tr[5][0], list_of_df_m3_tr[5][1], ['0','1'])
print_classification_report(lgbm_m3, list_of_df_m3_tr[5][0], list_of_df_m3_tr[5][1])

"""Zbior testowy"""

summary_model(lgbm_m3, list_of_df_m3_te[5][0], list_of_df_m3_te[5][1], ['0','1'])
print_classification_report(lgbm_m3, list_of_df_m3_te[5][0], list_of_df_m3_te[5][1])

plot_map_from_model(lgbm_m3, list_df_months[5], "Czerwiec - detekcja step (1) - niestep (0)")

"""Model podobny jakosciowo to poprzednich klasyfikatorow step - niestep.

### Zapisanie modeli
"""

model_lgbm_m1_path='/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/LightGBM/lgbm_m1'
model_lgbm_m2_path='/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/LightGBM/lgbm_m2'
model_lgbm_m2_7_path='/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/LightGBM/lgbm_m2_7'
model_lgbm_m3_path='/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/LightGBM/lgbm_m3'

with open(model_lgbm_m1_path, 'wb') as files:
  pickle.dump(lgbm_m1, files)

with open(model_lgbm_m2_path, 'wb') as files:
  pickle.dump(lgbm_m2, files)

with open(model_lgbm_m2_7_path, 'wb') as files:
  pickle.dump(lgbm_m2_7, files)

with open(model_lgbm_m3_path, 'wb') as files:
  pickle.dump(lgbm_m3, files)

"""## Uwzglednienie wartosci *lat* w modelu pustynia - niepustynia

W klasyfikacji pustynia - nie pustynia problematyczne wydaje sie klasyfikowanie zimnych pustyn wysunietych najbardziej na polnoc oraz bledna klasyfikacja obszarow nad Zatoka Meksykanska jako pustynie. Cecha majaca wplyw na polepszenie modelu przypuszczalnie moze byc kontekst geograficzny. W tym rozdziale podjeto probe rozszerzenia cech w modelu o *lat* czyli szerokosc geograficzna.

Na danych z lipca zbudujemy dwa modele: lasow losowych i LifhtGBM.

**Przygotowanie danych**
"""

july_an = list_of_df_all[6].loc[:,'lat':'SoilM_100_200cm']

july_X_tr, july_X_te, july_y_tr, july_y_te = train_test_split(july_an, y_m2, test_size=0.2, random_state=2024)

"""### Lasy losowe

Do strojenia hiperparametrow zostal uzyty ten sam zestaw cech jak w rozdziale o lasach losowych.
"""

gs_las_lat = GridSearchCV(RandomForestClassifier(random_state = 2024), cv = 5, param_grid = params_gs_las, scoring = 'accuracy')
gs_las_lat.fit(july_X_tr, july_y_tr)

las_m2_lat = RandomForestClassifier(random_state = 2024, **gs_las_lat.best_params_)

las_m2_lat.fit(july_X_tr, july_y_tr)

"""Zbior treningowy"""

summary_model(las_m2_lat, july_X_te, july_y_te, ['0','1'])
print_classification_report(las_m2_lat, july_X_te, july_y_te)

"""Zbior testowy"""

summary_model(las_m2_lat, july_X_te, july_y_te, ['0','1'])
print_classification_report(las_m2_lat, july_X_te, july_y_te)

df_july = list_df_months[6]
df_july['las_m2_lat'] = las_m2_lat.predict(df_july.loc[:,'lat':'SoilM_100_200cm'])
colormap_cluster = get_colormap([0, max(df_july.las_m2_lat.values)], ['darkgreen', 'yellow'])
plot_las_july = plot_map(df=df_july, parameter_name='las_m2_lat', colormap=colormap_cluster, title="Lipiec - detekcja pustynia (1) - niepustynia (0)", alpha=1)
output_notebook()
show(plot_las_july)

"""Model ma lepszy recall 89% (wieksze o o 9 p.p. od modelu drzew bez *lat*) oraz gorszy precision 70% (mniejsze o 19% p.p. od modelu drzew bez *lat*). Interpretujac powyzsza mape widzimy, ze ten model nie ma problemu z obszarami nad Zatoka Meksykanska. Zmniejszyla sie natomiast poprawnosc klasyfikacji zimnych pustyn.

### Light GBM

Do strojenia hiperparametrow zostal uzyty ten sam zestaw cech jak w rozdziale o modelach Light GBM.
"""

gs_lgbm_lat = GridSearchCV(LGBMClassifier(random_state = 2024), cv = 5, param_grid = params_gs_lgbm, scoring = 'accuracy')
gs_lgbm_lat.fit(july_X_tr, july_y_tr)

lgbm_m2_lat = LGBMClassifier(random_state = 2024, **gs_lgbm_lat.best_params_)

lgbm_m2_lat.fit(july_X_tr, july_y_tr)

"""Zbior treningowy"""

summary_model(lgbm_m2_lat, july_X_tr, july_y_tr, ['0','1'])
print_classification_report(lgbm_m2_lat, july_X_tr, july_y_tr)

"""Zbior testowy"""

summary_model(lgbm_m2_lat, july_X_te, july_y_te, ['0','1'])
print_classification_report(lgbm_m2_lat, july_X_te, july_y_te)

df_july['lgbm_m2_lat'] = lgbm_m2_lat.predict(df_july.loc[:,'lat':'SoilM_100_200cm'])
colormap_cluster = get_colormap([0, max(df_july.lgbm_m2_lat.values)], ['darkgreen', 'yellow'])
plot_lgbm_july = plot_map(df=df_july, parameter_name='lgbm_m2_lat', colormap=colormap_cluster, title="Lipiec - detekcja pustynia (1) - niepustynia (0)", alpha=1)
output_notebook()
show(plot_lgbm_july)

"""Model nieznacznie gorszy od modelu Light GBM bez cechy *lat*. Zmniejszyl sie problem klasyfikacji obszarow przy Zatoce Meksykanskiej, pogłebil problem zimnych pustyn.

### Zapisanie modeli
"""

model_las_m2_lat_path='/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/Modele_z_lat/las_m2_lat'
model_lgbm_m2_lat_path='/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/Modele_z_lat/lgbm_m2_lat'

with open(model_las_m2_lat_path, 'wb') as files:
  pickle.dump(las_m2_lat, files)

with open(model_lgbm_m2_lat_path, 'wb') as files:
  pickle.dump(lgbm_m2_lat, files)

"""## Podsumowanie

W ramach zadania zostało zbudowanychy 18 modeli klasyfikacji pustynia - niepustynia. Najlepsze wydaja sie modele:

* Lasów losowych na danych lipcowych - [sciezka do pliku]('/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/Lasy/las_m2_7')
* Light GBM na danych lipcowych - [sciezka do pliku]('/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/LightGBM/lgbm_m2_7')
* Lasów losowcych z cehcą *lat* na danych lipcowych- [sciezka do pliku]('/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/Modele_z_lat/las_m2_lat')

dla tych modeli accuracy wacha się w okolicach 91%, a wartość statytyski F1 w granicach 70%.

Dla klasyfikacji pustynia - step - inne najlepszy mode to las losowy na danych czerwcowych - [sciezka do pliku]('/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/Lasy/las_m1')

Dla klasyfikacji step - niestep najlepszy model to Light GLM na danych czerwcowych - [sciezka do pliku](/content/drive/MyDrive/BigMess/NASA/Modele/Klasyfikacja/LightGBM/lgbm_m3)
"""